/*
* This test is generated by AI:
* Gemini 3 Pro
*/

import toString from '../src/toString.js';

describe('toString', () => {
  // Test Case 1: String input 
  test('should return the string itself when input is a string', () => {
    expect(toString('hello')).toBe('hello');
  });

  // Test Case 2: Empty input 
  test('should return empty string when input is an empty string', () => {
    expect(toString('')).toBe(''); 
  });

  // Test Case 3: Positive number 
  test('should convert positive number to string', () => {
    expect(toString(1)).toBe('1');
  });

  // Test Case 4: Negative number 
  test('should convert negative number to string', () => {
    expect(toString(-1)).toBe('-1');
  });

  // Test Case 5: Negative zero 
  // Validates the specific logic: (result == '0' && (1 / value) == -INFINITY)
  test('should preserve the sign of negative zero', () => {
    expect(toString(-0)).toBe('-0');
  });

  // Test Case 6: Empty array 
  test('should return empty string for empty array', () => {
    expect(toString([])).toBe('');
  });

  // Test Case 7: Array with numbers 
  test('should convert array of numbers to comma-separated string', () => {
    expect(toString([1, 2, 3])).toBe('1,2,3');
  });

  // Test Case 8: Array with null 
  test('should handle null values within an array', () => {
    expect(toString([1, null, 3])).toBe('1,,3');
  });

  // Test Case 9: Nested array 
  test('should flatten and convert nested arrays', () => {
    expect(toString([[1, 2, 3], [4]])).toBe('1,2,3,4');
  });

  // Test Case 10: Deeply nested array (Dumb array) 
  test('should handle deeply nested single values', () => {
    expect(toString([[[1]]])).toBe('1');
  });
});